### ISSUE TITLE
baseSpeed/baseVelocity

### ISSUE THREAD

**Issue by GuusHamm** [GuusHamm/Call-of-Cactus#1]
Basevelocity and baseSpeed are both used and can be interchanged

**Comment by GuusHamm** [comment]
fuck dat, dit is geen probleem

**Comment by nino-vrijman** [comment]
Wat is jou probleem

**Comment by JimSanders96** [comment]
stelletje kut negers

**Comment by nino-vrijman** [comment]
je bent zelf een neger

**Comment by LiekeVanmulken** [comment]
dit is een feauture not a bug

**Comment by Jimbolul** [comment]
je moeder is een plopkoek

**Comment by teunw** [comment]
Y u do dis?

**Comment by binq1000** [comment]
We gebruiken BaseSpeed niet, terwijl we dit wel willen, i.p.v int baseVelocity = 10; willen we this.setBaseSpeed(10);
