### ISSUE TITLE
BossAi and normal AI do the same ammount of damage (both 20)

### ISSUE THREAD

**Issue by binq1000** [GuusHamm/Call-of-Cactus#120]

**Comment by GuusHamm** [comment]
@binq1000 Not sure if related but the player change role test is failing because the get damage apparently is not changing after role switch but seeing from the debugger it seems to work. Again not sure if related

**Comment by LiekeVanmulken** [comment]
The rolemultiplier is not being used in the getter therefor it doesn't change.
