### ISSUE TITLE
Using GDX Tiles for map

### ISSUE THREAD

**Issue by nino-vrijman** [GuusHamm/Call-of-Cactus#124]
In iteration 1 the map was hardcoded, our library has so called "Tiles" which help creating maps easier.

**Comment by LiekeVanmulken** [comment]
@nino-vrijman check ook de andere issue om een mapgenerator te maken.

**Comment by nino-vrijman** [comment]
Heb hier echt hulp bij nodig aangezien ik dit weekend niet beschikbaar ben. 
https://docs.google.com/document/d/1h_Ai8_l27CFtEnaZ9FvafmUoDT-5-4Uo4t8MWSQ-CKk/edit#

**Comment by nino-vrijman** [comment]
done
