### ISSUE TITLE
Port wave system to Game

### ISSUE THREAD

**Issue by teunw** [GuusHamm/Call-of-Cactus#17]

**Comment by GuusHamm** [comment]
Is this fixed? @binq1000 @woutie012006

**Comment by GuusHamm** [comment]
@Jimbolul

**Comment by LiekeVanmulken** [comment]
Not that I know of not completely I think,  I have no idea @binq1000 implemented this in gamescreen don't know if it should be ported or that it is complete

**Comment by GuusHamm** [comment]
@woutie012006 It should be in game

**Comment by nino-vrijman** [comment]
Willing to help implement this feature. Also would like to help to write some kind of algorithm for it.

**Comment by binq1000** [comment]
What is the idea of this one? I already made waves, is it done then? Or should i also make after x amount of waves a boss appears?

**Comment by GuusHamm** [comment]
@binq1000 The point of this one is that you made it in gamescreen it should be in game so as the title suggests we need to move it
