### ISSUE TITLE
Health is not being properly set.

### ISSUE THREAD

**Issue by LiekeVanmulken** [GuusHamm/Call-of-Cactus#264]
Health isn't being properly set in clientsideserver and not in takeDamage. This might be because of the copylist ( @binq1000  ).

**Comment by binq1000** [comment]
I'll check it out

**Comment by GuusHamm** [comment]
@binq1000 Jim is also looking into this

**Comment by binq1000** [comment]
at case heatlh in ClientSideServer HandleInputCHANGE, takeDamage is called instead of setHealth, is this correct with the send data? and shouldn't this case be renamed damage or something?

**Comment by GuusHamm** [comment]
@binq1000 We changed this today it didn't work with setHealth so i'm not sure if that's the problem

**Comment by GuusHamm** [comment]
@binq1000 I think the problem is that we change a value but then never put that back into the administration, resulting in the new value just being tossed away
