### ISSUE TITLE
End game implementation

### ISSUE THREAD

**Issue by GuusHamm** [GuusHamm/Call-of-Cactus#28]

**Comment by teunw** [comment]
This still needs to be trigged, condition tbd.

**Comment by nino-vrijman** [comment]
Would be easiest to end game based on a certain score amount for this iteration, that way we have to change little to none to the application (just a check after every score update to see if the score limit is surpassed).

**Comment by GuusHamm** [comment]
Agreed it still needs to still happen when the player dies

**Comment by LiekeVanmulken** [comment]
@nino-vrijman dit moet worden aangeroepen wanneer de speler 0 health heeft.

**Comment by nino-vrijman** [comment]
Has been implemented
