### ISSUE TITLE
Dying implentation

### ISSUE THREAD

**Issue by GuusHamm** [GuusHamm/Call-of-Cactus#29]

**Comment by GuusHamm** [comment]
This is for player but also bullets etc.

**Comment by GuusHamm** [comment]
@woutie012006 original issue

**Comment by LiekeVanmulken** [comment]
@guushamm dankje,  zou jij dit kunnen implementeren?

**Comment by GuusHamm** [comment]
@woutie012006 yeah sure

**Comment by GuusHamm** [comment]
isn't this done already?

**Comment by LiekeVanmulken** [comment]
@guushamm only if you implemented it.  No idea.

**Comment by GuusHamm** [comment]
@woutie012006 I haven't done that explicitly no, but what would you want it to do?

**Comment by LiekeVanmulken** [comment]
@GuusHamm  give a screen saying that you died with a score or something like that.  Also change the takes damage in human character, because it changed to 300 when health is 0 for debugging porpuses.

**Comment by GuusHamm** [comment]
Okay thanks, i'll fix that then

**Comment by LiekeVanmulken** [comment]
@GuusHamm ^updated that comment
