### ISSUE TITLE
Math accept 0 weird returns

### ISSUE THREAD

**Issue by LiekeVanmulken** [GuusHamm/Call-of-Cactus#3]
When calculating new values in calculatenewposition it cant handle 0, need to fix this.

**Comment by LiekeVanmulken** [comment]
also it is not using the math start (which should be to the right).

**Comment by LiekeVanmulken** [comment]
return (360 - currentanswer)%360

**Comment by GuusHamm** [comment]
Is this fixed?

**Comment by LiekeVanmulken** [comment]
nope not yet tested

**Comment by LiekeVanmulken** [comment]
will close it when it is tested and completely fixed

**Comment by GuusHamm** [comment]
@woutie012006 Okay

**Comment by LiekeVanmulken** [comment]
should be fixed, the tests work
