### ISSUE TITLE
Get the size(max X and Y value) of the window

### ISSUE THREAD

**Issue by binq1000** [GuusHamm/Call-of-Cactus#46]

**Comment by LiekeVanmulken** [comment]
wanna use a rectangle ?

**Comment by GuusHamm** [comment]
@woutie012006 Yeah sure

**Comment by nino-vrijman** [comment]
If we are using a 'Scene' (standard Java Class) for our game screen you can use: 'scene.getWidth()' and 'scene.getHeight()'
