### ISSUE TITLE
WASD beweegt character

### ISSUE THREAD

**Issue by teunw** [GuusHamm/Call-of-Cactus#5]

**Comment by GuusHamm** [comment]
@Jimbolul Is this fixed?

**Comment by LiekeVanmulken** [comment]
dit was toch al klaar 0.o

**Comment by GuusHamm** [comment]
@woutie012006 Ja maar niet getest

**Comment by LiekeVanmulken** [comment]
als je schuin gaat ga je sneller omdat de move twee keer wordt aangeroepen.

**Comment by GuusHamm** [comment]
Ik heb hier een issue voor geopend, ik heb het min of meer kunnen fixen maar de manier waarop we nu input afvangen zorgt het afvangen hiervan dat het personage floaty aanvoelt, dit is dus een won't fix
